### ISSUE TITLE
No users match for specified terms

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#159]
Hi Professor,

When i run get_users() method, i get the following error message:

Got error {"errors":[{"code":17,"message":"No user matches for specified terms."}]} 
sleeping for 15 minutes.

I made lesser than 5 calls in the 15 min window but yet it goes to sleep. 

What might be the reason for the error? I am constructing a string with the usernames and passing it to robust_request.

-Rittick

**Comment by davidghiurco** [comment]
When you read off the names from the file, did you strip off the newline character? because that will get read in as part of the screen_name and that's gonna cause you to not get matches.

Example: correct: 'realDonaldTrump' .... what you might have: 'realDonaldTrump\n'

I got the same error and I fixed it by stripping off the newline and then it worked.

As for robust_request...it is built so that when it gets ANY HTTP CODE other than 200 (a.k.a OK) then it will sleep. Rate limit exceeded might be code 403 but it will sleep for literally any other code other than 200. So it is working as intended.

**Comment by dipentrivedi** [comment]
I am getting the right tupple, but still getting the same error.
Error:
-----------------------------------------------------------------------------------------------------------------------------------------
['DrJillStein', 'GovGaryJohnson', 'HillaryClinton', 'realDonaldTrump']
Got error {"errors":[{"code":17,"message":"No user matches for specified terms."}]} 
sleeping for 15 minutes.
-----------------------------------------------------------------------------------------------------------------------------------------

**Comment by davidghiurco** [comment]
then that means you are not passing in the right parameters to robust_request.

Remember the type of 'params' is a dict (python dictionary) of parameters you want to query from the server. Make sure your parameters are in correct syntax / form. You might be passing in just a string, which would be incorrect

**Comment by dipentrivedi** [comment]
ohh...!! Thnx !!

**Comment by RittickDatta** [comment]
Issue resolved.
